version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.17.1
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            cd frontend
            npm install

      - run:
          name: Run tests
          command: |
            cd frontend
            npm test -- --watchAll=false

      - run:
          name: Build app
          command: |
            cd frontend
            npm run build

workflows:
  build-and-test:
    jobs:
      - build
