name: Frontend CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Navigate to frontend and install dependencies
        run: |
          cd frontend
          npm install

      - name: Run ESLint
        run: |
          cd frontend
          npx eslint . --ext .js,.jsx || true

      - name: Run npm audit
        run: |
          cd frontend
          npm audit --audit-level=moderate || true

      - name: Run tests
        run: |
          cd frontend
          npm test -- --watchAll=false || true

      - name: Build project
        run: |
          cd frontend
          npm run build
